[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "viewer"
showErrorDetails = false

[theme]
base="dark"
primaryColor="#00e599"
backgroundColor="#080d1a"
secondaryBackgroundColor="#0f172a"
textColor="#f8fafc"
font="sans serif"
